### ISSUE TITLE
"Set mode"-card error

### ISSUE THREAD

**Issue by erik-agens** [Allram/com.fladby.exvent#1]
Hi! Just trying this app and it looks very promising - thank you!
I created a flow that uses the "Set mode X"-card, however it returns an error saying `Flow Card not registered (type: action, id: eWind_mode_action)`.
Is there something in my setup that is not correct maybe?
Let me know if I can provide further details!

Takk skal du ha!

Erik

**Comment by Allram** [comment]
This will be fixed hopefully tonight or at the end of the weekend.

Just managed to be able to write to Modbus so i haven't implemented all of the flow features yet :)

**Comment by erik-agens** [comment]
Awesome! Thank you!
