### ISSUE TITLE
Add filter alarm when card

### ISSUE THREAD

**Issue by markusv** [Allram/com.fladby.exvent#10]
Is it possible to add a flow when card for filter alarms? That way homey can remind me when there is a filter alarm.

**Comment by Allram** [comment]
I will see what i can do about that.
Still learning how i implement all of the flow-stuff.

Will take a look at this after i have fixed the Trigger and AND-flow cards :)

**Comment by Allram** [comment]
Fixed in v2.14.0 https://github.com/Allram/com.fladby.exvent/commit/4f77a56155eff1c3beda85725dcccfd2ea8a2980
