### ISSUE TITLE
eWind -> iSLa

### ISSUE THREAD

**Issue by fishfisher** [Allram/com.fladby.exvent#17]
Jeg har måttet gå over fra å bruke eWind app til iSLa.
Får ikke da til å styre ventilasjonen lenger. Har du inntrykk av at det er noe som må gjøres for å få det opp og stå igjen?

**Comment by fishfisher** [comment]
Kan se ut til at jeg fikk lagt inn. Disregard:)

**Comment by Allram** [comment]
Testa det igjen selv her i dag tidlig. Fw 2.3.0 og nyere på iSLA skal fungere fint :)

**Comment by fishfisher** [comment]
Takk for at du sjekket! Jeg er også på 2.3.0 og nå ser det ut til å fungere! Måtte bare legge til på nytt etter jeg byttet modul:)
Tusen takk!
