### ISSUE TITLE
Problem with flow cards

### ISSUE THREAD

**Issue by afloden** [Allram/com.fladby.exvent#18]
Hi.

I just got an Exvent ventilation unit with eAir control. I've installed your app and paired it with the unit, and so far it works fine except from two problems:

1. Running an action from a flow card, e.g. "Set mode" produce an error and nothing happens. The error is "Flow Card not registered (type: action, id: status-mode_eAir)" .This seems to be the same as in issue #1 (except that was with eWind) .

2. Trigger card doesn't react: "When mode changed to ...." never triggers, even though I do change the mode on the unit's control panel.

I had a friend who is a developer take a look, and after some investigation he has three recommendations to the code:
* registerRunListener takes two parameters (args and state), whereas this app's code only declares one (args).
* The statement "use strict" would eliminate these kind of problems at compile time
* He also found that in onInit, the first and last line in registerFlowListeners shouldn't be there as they might result in the app becoming unstable. Instead, there is a method isFirstInit() that can be used for initalizations that should only happen once. This example is from Perplexity:

async onInit() {
  // Always perform necessary initializations
  this.registerListeners();

  // Perform first-time only actions
  if (this.isFirstInit()) {
    // Do first-time setup here
    await this.firstTimeSetup();
  }
}

I hope you have time to look into these problems.

Kind regards,
Asbjørn

**Comment by Allram** [comment]
I guess we also talked on email. This should be fixed with https://github.com/Allram/com.fladby.exvent/commit/9907566d6af668c0725b14da4985d7d45be2ea86

Please test with Homey App v3.1.2.

**Comment by Allram** [comment]
Regarding your other recommendations, i'm not a developer so those are much appreciated!

point 1: I will see if i can optimize some things here.
point 2: I will look into this.
point 3: i had to take it out of "onInit" and use flags if not it will not work on the older Homey's (don't know why).
